import { FieldItem } from './types'
// この項目はGoogle Spreadsheetで生成したJSONを利用するようにしてください。
// https://drive.google.com/open?id=1jfwHhto0gL5OECuNFQTtD0vbFqIjycksOg9l9RnBYIk
// コード上で変更しないでください。
const fieldItemList: FieldItem[] = [
  {
    category_id: 3702,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 656
  },
  {
    category_id: 3901,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 658
  },
  {
    category_id: 3902,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 659
  },
  {
    category_id: 3903,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 660
  },
  {
    category_id: 3904,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 661
  },
  {
    category_id: 4099,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 906
  },
  {
    category_id: 5202,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 105202
  },
  {
    category_id: 5204,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 105204
  },
  {
    category_id: 5206,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 105206
  },
  {
    category_id: 5249,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 105249
  },
  {
    category_id: 5250,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 105250
  },
  {
    category_id: 5269,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 105269
  },
  {
    category_id: 5401,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 1
  },
  {
    category_id: 5402,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 1
  },
  {
    category_id: 5403,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 1
  },
  {
    category_id: 5501,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 1100
  },
  {
    category_id: 5510,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 1102
  },
  {
    category_id: 5520,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 369
  },
  {
    category_id: 5530,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 370
  },
  {
    category_id: 10101,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '例) ニトリ ハイチェスト',
    sort: 1,
    format_id: 139
  },
  {
    category_id: 10102,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '例) GRAZIA ダイニングテーブル',
    sort: 1,
    format_id: 140
  },
  {
    category_id: 10103,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '例) メッシュチェア',
    sort: 1,
    format_id: 141
  },
  {
    category_id: 10108,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '例) 食器棚 96DB',
    sort: 1,
    format_id: 146
  },
  {
    category_id: 10110,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '例) L字型ソファ AQUA',
    sort: 1,
    format_id: 148
  },
  {
    category_id: 10111,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '例) テレビ台 クロノ90 DBR',
    sort: 1,
    format_id: 149
  },
  {
    category_id: 10112,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '例) 3面ドレッサー UK-DREAR2',
    sort: 1,
    format_id: 150
  },
  {
    category_id: 10113,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '例) 6段チェスト',
    sort: 1,
    format_id: 151
  },
  {
    category_id: 10114,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '例) キッチンカウンター',
    sort: 1,
    format_id: 152
  },
  {
    category_id: 10117,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '例) キッチンカウンター',
    sort: 1,
    format_id: 328
  },
  {
    category_id: 10203,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 157
  },
  {
    category_id: 10302,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 331
  },
  {
    category_id: 10303,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 332
  },
  {
    category_id: 10304,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 575
  },
  {
    category_id: 10305,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 576
  },
  {
    category_id: 10310,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 581
  },
  {
    category_id: 10402,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint:
      '取扱いは季節もの、ノンブランドなどはまとまった点数でのご依頼とさせて頂きます。',
    sort: 1,
    format_id: 335
  },
  {
    category_id: 10502,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint:
      '取扱いは季節もの、ノンブランドなどはまとまった点数でのご依頼とさせて頂きます。',
    sort: 1,
    format_id: 344
  },
  {
    category_id: 10718,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '例) ロエベの財布',
    sort: 1,
    format_id: 368
  },
  {
    category_id: 10901,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '例) シャープ 6ドア冷蔵庫 SJ-GT51C',
    sort: 1,
    format_id: 377
  },
  {
    category_id: 10902,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '例) コロナ ファンヒーター FH-G3217Y(S)',
    sort: 1,
    format_id: 378
  },
  {
    category_id: 10903,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '例) リンナイ KGM33NBEL 12A13A',
    sort: 1,
    format_id: 379
  },
  {
    category_id: 10904,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '例) パナソニック MC-PK18G',
    sort: 1,
    format_id: 380
  },
  {
    category_id: 10909,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '例) 東芝 石窯ドーム ER-PD7',
    sort: 1,
    format_id: 385
  },
  {
    category_id: 10910,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '例) 日立 ビートウォッシュ BW-V80B',
    sort: 1,
    format_id: 386
  },
  {
    category_id: 10911,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '例) パナソニック エオリア CS-227CF',
    sort: 1,
    format_id: 387
  },
  {
    category_id: 10913,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '例) パナソニック おどり炊き SR-PA107',
    sort: 1,
    format_id: 389
  },
  {
    category_id: 10916,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '例) パナソニック NP-TR9-W',
    sort: 1,
    format_id: 392
  },
  {
    category_id: 10917,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '例) アイリスオーヤマ ECOHLUX CL6D-5.0',
    sort: 1,
    format_id: 393
  },
  {
    category_id: 10919,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '例) シャープ 6ドア冷蔵庫 SJ-GT51C',
    sort: 1,
    format_id: 395
  },
  {
    category_id: 10930,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '例) シャープ AQUOS LC-50U45',
    sort: 1,
    format_id: 105420
  },
  {
    category_id: 11201,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 410
  },
  {
    category_id: 11205,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 414
  },
  {
    category_id: 11209,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 418
  },
  {
    category_id: 11210,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 419
  },
  {
    category_id: 11212,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 421
  },
  {
    category_id: 11213,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 422
  },
  {
    category_id: 11216,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 613
  },
  {
    category_id: 11230,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 1
  },
  {
    category_id: 11240,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 1
  },
  {
    category_id: 11255,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 1
  },
  {
    category_id: 11490,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 1
  },
  {
    category_id: 11498,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 1
  },
  {
    category_id: 11499,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 1
  },
  {
    category_id: 11507,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 634
  },
  {
    category_id: 11701,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 460
  },
  {
    category_id: 12002,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 635
  },
  {
    category_id: 12004,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 637
  },
  {
    category_id: 12005,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 638
  },
  {
    category_id: 12010,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 639
  },
  {
    category_id: 12101,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 476
  },
  {
    category_id: 12102,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 1
  },
  {
    category_id: 12103,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 478
  },
  {
    category_id: 12104,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 479
  },
  {
    category_id: 12105,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 480
  },
  {
    category_id: 12107,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 641
  },
  {
    category_id: 12108,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 1
  },
  {
    category_id: 12201,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 481
  },
  {
    category_id: 12301,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 482
  },
  {
    category_id: 12302,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 483
  },
  {
    category_id: 12305,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 486
  },
  {
    category_id: 12401,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 488
  },
  {
    category_id: 12402,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 489
  },
  {
    category_id: 12403,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 490
  },
  {
    category_id: 12404,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 491
  },
  {
    category_id: 12405,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 492
  },
  {
    category_id: 12406,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 493
  },
  {
    category_id: 12407,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 494
  },
  {
    category_id: 12408,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 643
  },
  {
    category_id: 12409,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 644
  },
  {
    category_id: 12410,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 1
  },
  {
    category_id: 12411,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 1
  },
  {
    category_id: 12801,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 411
  },
  {
    category_id: 12802,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 411
  },
  {
    category_id: 12803,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 501
  },
  {
    category_id: 12804,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 501
  },
  {
    category_id: 12805,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 1
  },
  {
    category_id: 12807,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 652
  },
  {
    category_id: 12901,
    field_name: 'メーカー名',
    field_key: 'manufacturer_name',
    type: 'select',
    required: true,
    rules: 'required|max:48',
    options: [
      'ブリヂストン',
      'ミズノ',
      'ダンロップ',
      'プロギア',
      'キャロウェイ',
      'タイトリスト',
      'テーラーメイド',
      'ウィルソン',
      'カムイ',
      'ホンマ',
      'セイコー',
      'キャスコ',
      'その他のメーカー'
    ],
    hint: '',
    sort: 1,
    format_id: 495
  },
  {
    category_id: 12902,
    field_name: 'メーカー名',
    field_key: 'manufacturer_name',
    type: 'select',
    required: true,
    rules: 'required|max:48',
    options: [
      'ブリヂストン',
      'ミズノ',
      'ダンロップ',
      'プロギア',
      'キャロウェイ',
      'タイトリスト',
      'テーラーメイド',
      'ウィルソン',
      'カムイ',
      'ホンマ',
      'セイコー',
      'キャスコ',
      'その他のメーカー'
    ],
    hint: '',
    sort: 1,
    format_id: 495
  },
  {
    category_id: 12903,
    field_name: 'メーカー名',
    field_key: 'manufacturer_name',
    type: 'select',
    required: true,
    rules: 'required|max:48',
    options: [
      'ブリヂストン',
      'ミズノ',
      'ダンロップ',
      'プロギア',
      'キャロウェイ',
      'タイトリスト',
      'テーラーメイド',
      'ウィルソン',
      'カムイ',
      'ホンマ',
      'セイコー',
      'キャスコ',
      'その他のメーカー'
    ],
    hint: '',
    sort: 1,
    format_id: 495
  },
  {
    category_id: 12904,
    field_name: 'メーカー名',
    field_key: 'manufacturer_name',
    type: 'select',
    required: true,
    rules: 'required|max:48',
    options: [
      'ブリヂストン',
      'ミズノ',
      'ダンロップ',
      'プロギア',
      'キャロウェイ',
      'タイトリスト',
      'テーラーメイド',
      'ウィルソン',
      'カムイ',
      'ホンマ',
      'セイコー',
      'キャスコ',
      'その他のメーカー'
    ],
    hint: '',
    sort: 1,
    format_id: 495
  },
  {
    category_id: 12905,
    field_name: 'メーカー名',
    field_key: 'manufacturer_name',
    type: 'select',
    required: true,
    rules: 'required|max:48',
    options: [
      'ブリヂストン',
      'ミズノ',
      'ダンロップ',
      'プロギア',
      'キャロウェイ',
      'タイトリスト',
      'テーラーメイド',
      'ウィルソン',
      'カムイ',
      'ホンマ',
      'セイコー',
      'キャスコ',
      'その他のメーカー'
    ],
    hint: '',
    sort: 1,
    format_id: 495
  },
  {
    category_id: 12906,
    field_name: 'メーカー名',
    field_key: 'manufacturer_name',
    type: 'text',
    required: true,
    rules: 'required|max:48',
    options: [],
    hint: '',
    sort: 1,
    format_id: 498
  },
  {
    category_id: 12907,
    field_name: 'メーカー名',
    field_key: 'manufacturer_name',
    type: 'text',
    required: true,
    rules: 'required|max:48',
    options: [],
    hint: '',
    sort: 1,
    format_id: 498
  },
  {
    category_id: 13001,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 454
  },
  {
    category_id: 13002,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 454
  },
  {
    category_id: 13003,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 454
  },
  {
    category_id: 13101,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 455
  },
  {
    category_id: 13102,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 456
  },
  {
    category_id: 13201,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 501
  },
  {
    category_id: 13202,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 501
  },
  {
    category_id: 13302,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 501
  },
  {
    category_id: 13303,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 501
  },
  {
    category_id: 13304,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 501
  },
  {
    category_id: 13403,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 371
  },
  {
    category_id: 13404,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 372
  },
  {
    category_id: 13405,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 373
  },
  {
    category_id: 13406,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 374
  },
  {
    category_id: 13599,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 1
  },
  {
    category_id: 13601,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 528
  },
  {
    category_id: 56010,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 396
  },
  {
    category_id: 56020,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 397
  },
  {
    category_id: 56030,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 1
  },
  {
    category_id: 57010,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 399
  },
  {
    category_id: 57020,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 400
  },
  {
    category_id: 57040,
    field_name: 'パーツ種類',
    field_key: 'parts_type',
    type: 'select',
    required: true,
    rules: 'required|max:24',
    options: [
      'CPU',
      'メモリ',
      'ハードディスク',
      'マザーボード',
      'カード',
      'ケース'
    ],
    hint: '',
    sort: 1,
    format_id: 1000
  },
  {
    category_id: 57050,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 1,
    format_id: 405
  },
  {
    category_id: 3702,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 3901,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 3902,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 3903,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 3904,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 4099,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 5202,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 5204,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 5206,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 5249,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 5250,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 5269,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 5401,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 5402,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 5403,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 5501,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 5510,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 5520,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 5530,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 10101,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 10102,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 10103,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 10108,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 10110,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 10111,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 10112,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 10113,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 10114,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 10117,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 10203,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 10302,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 10303,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 10304,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 10305,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 10310,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 10402,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 10502,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 10718,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 10901,
    field_name: '製造年数',
    field_key: 'manufacturing_years',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 2020年製',
    sort: 2,
    format_id: 504
  },
  {
    category_id: 10902,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 10903,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 10904,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 10909,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 10910,
    field_name: '製造年数',
    field_key: 'manufacturing_years',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 2020年製',
    sort: 2,
    format_id: 502
  },
  {
    category_id: 10911,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 10913,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 10916,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 10917,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 10919,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 10930,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 11201,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 11205,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 11209,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 11210,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 11212,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 11213,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 11216,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 11230,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 11240,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 11255,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 11490,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 11498,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 11499,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 11507,
    field_name: '発行年',
    field_key: 'publication_year',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '',
    sort: 2,
    format_id: 111
  },
  {
    category_id: 11701,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 12002,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 12004,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 12005,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 12010,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 12101,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 12102,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 12103,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 12104,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 12105,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 12107,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 12108,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 12201,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 12301,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 12302,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 12305,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 12401,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 12402,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 12403,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 12404,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 12405,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 12407,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 12409,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 12410,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 12411,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 12801,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 12802,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 12803,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 12804,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 12805,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 12807,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 12901,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 2,
    format_id: 496
  },
  {
    category_id: 12902,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 2,
    format_id: 496
  },
  {
    category_id: 12903,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 2,
    format_id: 496
  },
  {
    category_id: 12904,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 2,
    format_id: 496
  },
  {
    category_id: 12905,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 2,
    format_id: 496
  },
  {
    category_id: 12906,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 2,
    format_id: 496
  },
  {
    category_id: 12907,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 2,
    format_id: 501
  },
  {
    category_id: 13001,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 13002,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 13003,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 13101,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 13102,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 13201,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 13202,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 13302,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 13303,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 13304,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 13403,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 13404,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 13405,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 13406,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 13599,
    field_name: '型番',
    field_key: 'product_id',
    type: 'text',
    required: true,
    rules: 'required|max:48',
    options: [],
    hint: '',
    sort: 2,
    format_id: 10047
  },
  {
    category_id: 56010,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 56020,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 56030,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 57010,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 57020,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 57040,
    field_name: '商品名',
    field_key: 'title',
    type: 'text',
    required: true,
    rules: 'required|max:500',
    options: [],
    hint: '',
    sort: 2,
    format_id: 1002
  },
  {
    category_id: 57050,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 2,
    format_id: 2
  },
  {
    category_id: 10304,
    field_name: '数量',
    field_key: 'quantity',
    type: 'text',
    required: true,
    rules: 'required|max:48',
    options: [],
    hint: '',
    sort: 3,
    format_id: 582
  },
  {
    category_id: 10305,
    field_name: '数量',
    field_key: 'quantity',
    type: 'text',
    required: true,
    rules: 'required|max:48',
    options: [],
    hint: '',
    sort: 3,
    format_id: 582
  },
  {
    category_id: 10901,
    field_name: '容量',
    field_key: 'capacity',
    type: 'text',
    required: true,
    rules: 'required|max:48',
    options: [],
    hint: '例) 365L',
    sort: 3,
    format_id: 508
  },
  {
    category_id: 12901,
    field_name: '傷の程度',
    field_key: 'damage',
    type: 'select',
    required: true,
    rules: 'required|max:48',
    options: [
      '未使用',
      '傷なし',
      '目立たない傷がある',
      '小さいがはっきりわかる傷がある',
      '深い傷がある'
    ],
    hint: '',
    sort: 3,
    format_id: 497
  },
  {
    category_id: 12902,
    field_name: '傷の程度',
    field_key: 'damage',
    type: 'select',
    required: true,
    rules: 'required|max:48',
    options: [
      '未使用',
      '傷なし',
      '目立たない傷がある',
      '小さいがはっきりわかる傷がある',
      '深い傷がある'
    ],
    hint: '',
    sort: 3,
    format_id: 497
  },
  {
    category_id: 12903,
    field_name: '傷の程度',
    field_key: 'damage',
    type: 'select',
    required: true,
    rules: 'required|max:48',
    options: [
      '未使用',
      '傷なし',
      '目立たない傷がある',
      '小さいがはっきりわかる傷がある',
      '深い傷がある'
    ],
    hint: '',
    sort: 3,
    format_id: 497
  },
  {
    category_id: 12904,
    field_name: '傷の程度',
    field_key: 'damage',
    type: 'select',
    required: true,
    rules: 'required|max:48',
    options: [
      '未使用',
      '傷なし',
      '目立たない傷がある',
      '小さいがはっきりわかる傷がある',
      '深い傷がある'
    ],
    hint: '',
    sort: 3,
    format_id: 497
  },
  {
    category_id: 12905,
    field_name: '傷の程度',
    field_key: 'damage',
    type: 'select',
    required: true,
    rules: 'required|max:48',
    options: [
      '未使用',
      '傷なし',
      '目立たない傷がある',
      '小さいがはっきりわかる傷がある',
      '深い傷がある'
    ],
    hint: '',
    sort: 3,
    format_id: 497
  },
  {
    category_id: 12906,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 3,
    format_id: 2
  },
  {
    category_id: 12907,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 3,
    format_id: 2
  },
  {
    category_id: 57040,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 3,
    format_id: 2
  },
  {
    category_id: 5202,
    field_name: 'メーカー名',
    field_key: 'manufacturer_name',
    type: 'text',
    required: true,
    rules: 'required|max:48',
    options: [],
    hint: '',
    sort: 4,
    format_id: 498
  },
  {
    category_id: 5204,
    field_name: 'メーカー名',
    field_key: 'manufacturer_name',
    type: 'text',
    required: true,
    rules: 'required|max:48',
    options: [],
    hint: '',
    sort: 4,
    format_id: 498
  },
  {
    category_id: 5206,
    field_name: 'メーカー名',
    field_key: 'manufacturer_name',
    type: 'text',
    required: true,
    rules: 'required|max:48',
    options: [],
    hint: '',
    sort: 4,
    format_id: 498
  },
  {
    category_id: 5249,
    field_name: 'メーカー名',
    field_key: 'manufacturer_name',
    type: 'text',
    required: true,
    rules: 'required|max:48',
    options: [],
    hint: '',
    sort: 4,
    format_id: 498
  },
  {
    category_id: 5250,
    field_name: 'メーカー名',
    field_key: 'manufacturer_name',
    type: 'text',
    required: true,
    rules: 'required|max:48',
    options: [],
    hint: '',
    sort: 4,
    format_id: 498
  },
  {
    category_id: 5269,
    field_name: 'メーカー名',
    field_key: 'manufacturer_name',
    type: 'text',
    required: true,
    rules: 'required|max:48',
    options: [],
    hint: '',
    sort: 4,
    format_id: 498
  },
  {
    category_id: 5501,
    field_name: '種別',
    field_key: 'gold_type',
    type: 'select',
    required: true,
    rules: 'required|max:24',
    options: ['24金（K24）', '22金（K22）', '18金（K18）', '14金（K14）'],
    hint: '',
    sort: 4,
    format_id: 1104
  },
  {
    category_id: 5510,
    field_name: '種別',
    field_key: 'gold_type',
    type: 'select',
    required: true,
    rules: 'required|max:24',
    options: [
      'プラチナ1000（Pt1000）',
      'プラチナ950（Pt950）',
      'プラチナ900（Pt900）',
      'プラチナ850（Pt850）'
    ],
    hint: '',
    sort: 4,
    format_id: 1106
  },
  {
    category_id: 11499,
    field_name: '箱・ケース',
    field_key: 'case',
    type: 'select',
    required: true,
    rules: 'required|max:100',
    options: ['有', '無', '一部破損'],
    hint: '',
    sort: 4,
    format_id: 684
  },
  {
    category_id: 12406,
    field_name: 'メーカー',
    field_key: 'manufacturer',
    type: 'text',
    required: true,
    rules: 'required|max:24',
    options: [],
    hint: '',
    sort: 4,
    format_id: 37
  },
  {
    category_id: 12408,
    field_name: 'メーカー',
    field_key: 'manufacturer',
    type: 'text',
    required: true,
    rules: 'required|max:24',
    options: [],
    hint: '',
    sort: 4,
    format_id: 37
  },
  {
    category_id: 12901,
    field_name: 'クラブの長さ',
    field_key: 'graph_length',
    type: 'text',
    required: true,
    rules: 'required|max:48',
    options: [],
    hint: '例)45インチ',
    sort: 4,
    format_id: 509
  },
  {
    category_id: 13599,
    field_name: '購入時期',
    field_key: 'purchase_time',
    type: 'text',
    required: true,
    rules: 'required|max:12',
    options: [],
    hint: '例) 「2020年1月」「2019年後半」',
    sort: 4,
    format_id: 2
  },
  {
    category_id: 3901,
    field_name: '自転車種類',
    field_key: 'bicycle_type',
    type: 'select',
    required: true,
    rules: 'required|max:24',
    options: [
      '電動自転車',
      'シティサイクル',
      '折りたたみ自転車',
      'マウンテンバイク',
      '子供用自転車',
      'BMX',
      'ロードサイクル',
      'クロスバイク',
      '一輪車',
      'その他'
    ],
    hint: '',
    sort: 5,
    format_id: 698
  },
  {
    category_id: 5202,
    field_name: '型番',
    field_key: 'product_id',
    type: 'text',
    required: true,
    rules: 'required|max:48',
    options: [],
    hint: '',
    sort: 5,
    format_id: 10047
  },
  {
    category_id: 5204,
    field_name: '型番',
    field_key: 'product_id',
    type: 'text',
    required: true,
    rules: 'required|max:48',
    options: [],
    hint: '',
    sort: 5,
    format_id: 10047
  },
  {
    category_id: 5206,
    field_name: '機種名',
    field_key: 'model_name',
    type: 'text',
    required: true,
    rules: 'required|max:48',
    options: [],
    hint: '',
    sort: 5,
    format_id: 1201
  },
  {
    category_id: 5250,
    field_name: '機種名',
    field_key: 'model_name',
    type: 'text',
    required: true,
    rules: 'required|max:48',
    options: [],
    hint: '',
    sort: 5,
    format_id: 1201
  },
  {
    category_id: 5501,
    field_name: 'タイプ',
    field_key: 'type',
    type: 'select',
    required: true,
    rules: 'required|max:24',
    options: [
      'インゴット',
      'リング',
      'ピアス・イアリング',
      'ネックレス',
      'ブレスレット',
      'コイン・メダル',
      '壊れたアクセサリー',
      'その他'
    ],
    hint: '',
    sort: 5,
    format_id: 1110
  },
  {
    category_id: 5510,
    field_name: 'タイプ',
    field_key: 'type',
    type: 'select',
    required: true,
    rules: 'required|max:24',
    options: [
      'インゴット',
      'リング',
      'ピアス・イアリング',
      'ネックレス',
      'ブレスレット',
      'コイン・メダル',
      '壊れたアクセサリー',
      'その他'
    ],
    hint: '',
    sort: 5,
    format_id: 1110
  },
  {
    category_id: 10718,
    field_name: '保証書、ギャランティーカード',
    field_key: 'warranty',
    type: 'radio',
    required: true,
    rules: 'required|max:100',
    options: [
      { label: '有', value: '有' },
      { label: '無', value: '無' }
    ],
    hint: '保証書、ギャランティーカードの有無を選択してください',
    sort: 5,
    format_id: 517
  },
  {
    category_id: 12901,
    field_name: 'シャフトフレックス',
    field_key: 'shaft_flex',
    type: 'text',
    required: true,
    rules: 'required|max:48',
    options: [],
    hint: '例)R300  ※シャフトの硬',
    sort: 5,
    format_id: 510
  },
  {
    category_id: 3702,
    field_name: '使用距離',
    field_key: 'usable_distance',
    type: 'text',
    required: true,
    rules: 'required|max:24',
    options: [],
    hint: '例) 約6,000Km使用',
    sort: 6,
    format_id: 691
  },
  {
    category_id: 5206,
    field_name: '型式・型番',
    field_key: 'product_id',
    type: 'text',
    required: true,
    rules: 'required|max:48',
    options: [],
    hint: '',
    sort: 6,
    format_id: 1200
  },
  {
    category_id: 5250,
    field_name: '型式・型番',
    field_key: 'product_id',
    type: 'text',
    required: true,
    rules: 'required|max:48',
    options: [],
    hint: '',
    sort: 6,
    format_id: 1200
  },
  {
    category_id: 12901,
    field_name: 'シャフト交換（リシャフト）',
    field_key: 'reshaft',
    type: 'radio',
    required: true,
    rules: 'required|max:48',
    options: [
      { label: '有', value: '有' },
      { label: '無', value: '無' }
    ],
    hint: 'シャフト交換をした場合は有を選択してください',
    sort: 6,
    format_id: 511
  },
  {
    category_id: 13599,
    field_name: '保証書、ギャランティーカード',
    field_key: 'warranty',
    type: 'radio',
    required: true,
    rules: 'required|max:100',
    options: [
      { label: '有', value: '有' },
      { label: '無', value: '無' }
    ],
    hint: '保証書、ギャランティーカードの有無を選択してください',
    sort: 6,
    format_id: 517
  },
  {
    category_id: 5206,
    field_name: '年式',
    field_key: 'model_year',
    type: 'text',
    required: true,
    rules: 'required|max:10',
    options: [],
    hint: '不明の場合は不明と入力してください',
    sort: 7,
    format_id: 556
  },
  {
    category_id: 5250,
    field_name: '年式',
    field_key: 'model_year',
    type: 'text',
    required: true,
    rules: 'required|max:10',
    options: [],
    hint: '不明の場合は不明と入力してください',
    sort: 7,
    format_id: 556
  },
  {
    category_id: 10909,
    field_name: 'オーブン機能',
    field_key: 'opon_mode',
    type: 'radio',
    required: true,
    rules: 'required|max:100',
    options: [
      { label: '有', value: '有' },
      { label: '無', value: '無' }
    ],
    hint: '',
    sort: 7,
    format_id: 75
  },
  {
    category_id: 10910,
    field_name: '容量',
    field_key: 'capacity',
    type: 'select',
    required: true,
    rules: 'required|max:100',
    options: [
      '3.8kg',
      '4.0kg',
      '4.2kg',
      '5.0kg',
      '6.0kg',
      '6.5kg',
      '7.0kg',
      'その他'
    ],
    hint:
      'フタの裏（二槽式は脱水槽のフタの裏）に表記されている最大容量。例）5.0Kg',
    sort: 7,
    format_id: 76
  },
  {
    category_id: 12405,
    field_name: '動作',
    field_key: 'operation',
    type: 'select',
    required: true,
    rules: 'required|max:100',
    options: ['問題なし', '難あり', '動作せず'],
    hint: '',
    sort: 7,
    format_id: 63
  },
  {
    category_id: 5202,
    field_name: '動作',
    field_key: 'operation',
    type: 'radio',
    required: true,
    rules: 'required|max:100',
    options: [
      { label: '問題ナシ', value: '問題ナシ' },
      { label: '問題アリ', value: '問題アリ' }
    ],
    hint: '',
    sort: 8,
    format_id: 9106
  },
  {
    category_id: 5204,
    field_name: '動作',
    field_key: 'operation',
    type: 'radio',
    required: true,
    rules: 'required|max:100',
    options: [
      { label: '問題ナシ', value: '問題ナシ' },
      { label: '問題アリ', value: '問題アリ' }
    ],
    hint: '',
    sort: 8,
    format_id: 9106
  },
  {
    category_id: 5249,
    field_name: '動作',
    field_key: 'operation',
    type: 'radio',
    required: true,
    rules: 'required|max:100',
    options: [
      { label: '問題ナシ', value: '問題ナシ' },
      { label: '問題アリ', value: '問題アリ' }
    ],
    hint: '',
    sort: 8,
    format_id: 9106
  },
  {
    category_id: 5269,
    field_name: '動作',
    field_key: 'operation',
    type: 'radio',
    required: true,
    rules: 'required|max:100',
    options: [
      { label: '問題ナシ', value: '問題ナシ' },
      { label: '問題アリ', value: '問題アリ' }
    ],
    hint: '',
    sort: 8,
    format_id: 9106
  },
  {
    category_id: 5401,
    field_name: '動作',
    field_key: 'operation',
    type: 'radio',
    required: true,
    rules: 'required|max:100',
    options: [
      { label: '問題ナシ', value: '問題ナシ' },
      { label: '問題アリ', value: '問題アリ' }
    ],
    hint: '',
    sort: 8,
    format_id: 9106
  },
  {
    category_id: 5402,
    field_name: '動作',
    field_key: 'operation',
    type: 'radio',
    required: true,
    rules: 'required|max:100',
    options: [
      { label: '問題ナシ', value: '問題ナシ' },
      { label: '問題アリ', value: '問題アリ' }
    ],
    hint: '',
    sort: 8,
    format_id: 9106
  },
  {
    category_id: 5403,
    field_name: '動作',
    field_key: 'operation',
    type: 'radio',
    required: true,
    rules: 'required|max:100',
    options: [
      { label: '問題ナシ', value: '問題ナシ' },
      { label: '問題アリ', value: '問題アリ' }
    ],
    hint: '',
    sort: 8,
    format_id: 9106
  },
  {
    category_id: 10930,
    field_name: '動作',
    field_key: 'operation',
    type: 'radio',
    required: true,
    rules: 'required|max:100',
    options: [
      { label: '問題ナシ', value: '問題ナシ' },
      { label: '問題アリ', value: '問題アリ' }
    ],
    hint: '',
    sort: 8,
    format_id: 9106
  },
  {
    category_id: 11205,
    field_name: 'リモコン',
    field_key: 'remote_controller',
    type: 'select',
    required: true,
    rules: 'required|max:100',
    options: ['純正リモコン有', '他社製リモコン有', '無'],
    hint: '',
    sort: 8,
    format_id: 69
  },
  {
    category_id: 11212,
    field_name: '動作',
    field_key: 'operation',
    type: 'select',
    required: true,
    rules: 'required|max:100',
    options: ['問題なし', '難あり', '動作せず'],
    hint: '',
    sort: 8,
    format_id: 63
  },
  {
    category_id: 11213,
    field_name: '動作',
    field_key: 'operation',
    type: 'select',
    required: true,
    rules: 'required|max:100',
    options: ['問題なし', '難あり', '動作せず'],
    hint: '',
    sort: 8,
    format_id: 63
  },
  {
    category_id: 11230,
    field_name: '動作',
    field_key: 'operation',
    type: 'radio',
    required: true,
    rules: 'required|max:100',
    options: [
      { label: '問題ナシ', value: '問題ナシ' },
      { label: '問題アリ', value: '問題アリ' }
    ],
    hint: '',
    sort: 8,
    format_id: 9106
  },
  {
    category_id: 11240,
    field_name: '動作',
    field_key: 'operation',
    type: 'radio',
    required: true,
    rules: 'required|max:100',
    options: [
      { label: '問題ナシ', value: '問題ナシ' },
      { label: '問題アリ', value: '問題アリ' }
    ],
    hint: '',
    sort: 8,
    format_id: 9106
  },
  {
    category_id: 11255,
    field_name: '動作',
    field_key: 'operation',
    type: 'radio',
    required: true,
    rules: 'required|max:100',
    options: [
      { label: '問題ナシ', value: '問題ナシ' },
      { label: '問題アリ', value: '問題アリ' }
    ],
    hint: '',
    sort: 8,
    format_id: 9106
  },
  {
    category_id: 12402,
    field_name: '動作',
    field_key: 'operation',
    type: 'select',
    required: true,
    rules: 'required|max:100',
    options: ['問題なし', '難あり', '動作せず'],
    hint: '',
    sort: 8,
    format_id: 63
  },
  {
    category_id: 12403,
    field_name: '動作',
    field_key: 'operation',
    type: 'select',
    required: true,
    rules: 'required|max:100',
    options: ['問題なし', '難あり', '動作せず'],
    hint: '',
    sort: 8,
    format_id: 63
  },
  {
    category_id: 12404,
    field_name: '動作',
    field_key: 'operation',
    type: 'select',
    required: true,
    rules: 'required|max:100',
    options: ['問題なし', '難あり', '動作せず'],
    hint: '',
    sort: 8,
    format_id: 63
  },
  {
    category_id: 12407,
    field_name: '動作',
    field_key: 'operation',
    type: 'select',
    required: true,
    rules: 'required|max:100',
    options: ['問題なし', '難あり', '動作せず'],
    hint: '',
    sort: 8,
    format_id: 63
  },
  {
    category_id: 12410,
    field_name: '動作',
    field_key: 'operation',
    type: 'radio',
    required: true,
    rules: 'required|max:100',
    options: [
      { label: '問題ナシ', value: '問題ナシ' },
      { label: '問題アリ', value: '問題アリ' }
    ],
    hint: '',
    sort: 8,
    format_id: 9106
  },
  {
    category_id: 12411,
    field_name: '動作',
    field_key: 'operation',
    type: 'radio',
    required: true,
    rules: 'required|max:100',
    options: [
      { label: '問題ナシ', value: '問題ナシ' },
      { label: '問題アリ', value: '問題アリ' }
    ],
    hint: '',
    sort: 8,
    format_id: 9106
  },
  {
    category_id: 12901,
    field_name: 'ロフト',
    field_key: 'loft',
    type: 'select',
    required: true,
    rules: 'required|max:48',
    options: [
      '6°以下',
      '6.5°',
      '7°',
      '7.5°',
      '8°',
      '8.5°',
      '9°',
      '9.5°',
      '10°',
      '10.5°',
      '１1°',
      '11.5°',
      '12°以上'
    ],
    hint: 'ロフトの角度を選択してください',
    sort: 8,
    format_id: 513
  },
  {
    category_id: 4099,
    field_name: '使用期間',
    field_key: 'usable_period ',
    type: 'select',
    required: true,
    rules: 'required|max:24',
    options: ['未使用', '半年未満', '半年以上1年未満', '1年以上'],
    hint: '',
    sort: 9,
    format_id: 940
  },
  {
    category_id: 10910,
    field_name: '乾燥機',
    field_key: 'dryer',
    type: 'radio',
    required: true,
    rules: 'required|max:100',
    options: [
      { label: '有', value: '有' },
      { label: '無', value: '無' }
    ],
    hint: '',
    sort: 9,
    format_id: 78
  },
  {
    category_id: 10930,
    field_name: 'リモコン',
    field_key: 'remote_controller',
    type: 'select',
    required: true,
    rules: 'required|max:100',
    options: ['純正リモコン有', '他社製リモコン有', '無'],
    hint: '',
    sort: 9,
    format_id: 69
  },
  {
    category_id: 11205,
    field_name: '動作',
    field_key: 'operation',
    type: 'select',
    required: true,
    rules: 'required|max:100',
    options: ['問題なし', '難あり', '動作せず'],
    hint: '',
    sort: 9,
    format_id: 63
  },
  {
    category_id: 11209,
    field_name: '動作',
    field_key: 'operation',
    type: 'select',
    required: true,
    rules: 'required|max:100',
    options: ['問題なし', '難あり', '動作せず'],
    hint: '',
    sort: 9,
    format_id: 63
  },
  {
    category_id: 11230,
    field_name: 'リモコン',
    field_key: 'remote_controller',
    type: 'select',
    required: true,
    rules: 'required|max:100',
    options: ['純正リモコン有', '他社製リモコン有', '無'],
    hint: '',
    sort: 9,
    format_id: 69
  },
  {
    category_id: 11240,
    field_name: 'リモコン',
    field_key: 'remote_controller',
    type: 'select',
    required: true,
    rules: 'required|max:100',
    options: ['純正リモコン有', '他社製リモコン有', '無'],
    hint: '',
    sort: 9,
    format_id: 69
  },
  {
    category_id: 12401,
    field_name: '動作',
    field_key: 'operation',
    type: 'select',
    required: true,
    rules: 'required|max:100',
    options: ['問題なし', '難あり', '動作せず'],
    hint: '',
    sort: 9,
    format_id: 63
  },
  {
    category_id: 5206,
    field_name: '可動',
    field_key: 'movable',
    type: 'radio',
    required: true,
    rules: 'required|max:4',
    options: [
      { label: '可動', value: '可動' },
      { label: '不動', value: '不動' }
    ],
    hint: '',
    sort: 10,
    format_id: 561
  },
  {
    category_id: 5250,
    field_name: '動作',
    field_key: 'operation',
    type: 'radio',
    required: true,
    rules: 'required|max:100',
    options: [
      { label: '問題ナシ', value: '問題ナシ' },
      { label: '問題アリ', value: '問題アリ' }
    ],
    hint: '',
    sort: 10,
    format_id: 9106
  },
  {
    category_id: 10911,
    field_name: 'リモコン',
    field_key: 'remote_controller',
    type: 'select',
    required: true,
    rules: 'required|max:100',
    options: ['純正リモコン有', '他社製リモコン有', '無'],
    hint: '',
    sort: 10,
    format_id: 69
  },
  {
    category_id: 11201,
    field_name: '動作',
    field_key: 'operation',
    type: 'select',
    required: true,
    rules: 'required|max:100',
    options: ['問題なし', '難あり', '動作せず'],
    hint: '',
    sort: 10,
    format_id: 63
  },
  {
    category_id: 11210,
    field_name: '動作',
    field_key: 'operation',
    type: 'select',
    required: true,
    rules: 'required|max:100',
    options: ['問題なし', '難あり', '動作せず'],
    hint: '',
    sort: 10,
    format_id: 63
  },
  {
    category_id: 11210,
    field_name: 'リモコン',
    field_key: 'remote_controller',
    type: 'select',
    required: true,
    rules: 'required|max:100',
    options: ['純正リモコン有', '他社製リモコン有', '無'],
    hint: '',
    sort: 11,
    format_id: 69
  },
  {
    category_id: 10910,
    field_name: '使用場所',
    field_key: 'usable_space',
    type: 'radio',
    required: true,
    rules: 'required|max:10',
    options: [
      { label: '屋内', value: '屋内' },
      { label: '屋外', value: '屋外' }
    ],
    hint: '',
    sort: 12,
    format_id: 550
  },
  {
    category_id: 12805,
    field_name: '使用距離',
    field_key: 'usable_distance',
    type: 'text',
    required: true,
    rules: 'required|max:24',
    options: [],
    hint: '例) 約6,000Km使用',
    sort: 12,
    format_id: 691
  }
]

export default fieldItemList
